### ISSUE TITLE
Polish up Subsistence API

### ISSUE THREAD

**Issue by TheMrIron2** [Game-Fusion/CrossBow#2]
Subsistence is great for basic animations across the screen, but say if, for example, if I only wanted a wave to go to a certain point on the screen I can't make it only go out to that point, it has to go the whole way across. I'll need help with that. Any other features, please add in your own time.

**Comment by byte-chan** [comment]
your own time.
what do i win

**Comment by TheMrIron2** [comment]
You win that warm feeling of accomplishment with your time. I'll do this myself adding functions from GPU for efficient drawing.
