### ISSUE TITLE
[Games] Host games through our servers?

### ISSUE THREAD

**Issue by TheMrIron2** [Game-Fusion/CrossBow#4]
If somebody here was good at rednet, we could change P2P [peer-to-peer] games into server games, for example NitroChess. NitroChess connects to the opponent using a P2P connection. This means there is just messages sent back and forward between them, making it messy. By adding in a server as a middle man, it would mean player 1 uploads his move to the server and player 2 downloads that move, and vice versa, rather than a flurry of messages sent directly to each other. This would make this more efficient and it would put our servers to use (for once, lol).

**Comment by byte-chan** [comment]
ew, rednet
k no

**Comment by TheMrIron2** [comment]
modem

**Comment by TheMrIron2** [comment]
I'll add this to the Projects board
